[package]
name = "proxyvpn-proxy"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
httparse.workspace = true
libc.workspace = true
tokio.workspace = true
url.workspace = true
